# Generated by Django 5.1.4 on 2024-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='camping_item_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
