# Generated by Django 5.1.4 on 2024-12-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Sekaran, Gunungpati, Semarang', verbose_name='Address')),
                ('phone', models.CharField(default='+62 81217886415', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(default='jamescamp@gmail.com', max_length=254, verbose_name='Email')),
                ('heading', models.CharField(default='Welcome to Jamescamp', max_length=200, verbose_name='Heading')),
                ('description', models.TextField(default='Kami adalah penyedia alat camping terpercaya yang berdedikasi untuk menghadirkan pengalaman alam terbuka yang tak terlupakan. Didirikan dengan semangat cinta petualangan, James Camp memahami bahwa kualitas peralatan dapat membuat perbedaan besar dalam setiap perjalanan outdoor Anda.', verbose_name='Description')),
                ('link_text', models.CharField(default='Search Item', max_length=100, verbose_name='Button Text')),
                ('link_url', models.URLField(default='#', verbose_name='Button URL')),
            ],
        ),
    ]
